### ISSUE TITLE
Add audios for Japanese translation.

### ISSUE THREAD

**Issue by roshniRam** [NJACKWinterOfCode/Learn-Japanese#1]

**Comment by Kstheking** [comment]
Audios of the Japanese words' pronunciation?

**Comment by roshniRam** [comment]
Yes

**Comment by saurabhshadow** [comment]
Is this issue closed?

**Comment by roshniRam** [comment]
Nope

**Comment by roshniRam** [comment]
Yeah sure

**Comment by saurabhshadow** [comment]
I can just add the audio files or have to add html javascript menu system?

**Comment by saurabhshadow** [comment]
> _No description provided._
It's done!
# #25

**Comment by saurabhshadow** [comment]
I have added the audios #25
please have a look!
