### ISSUE TITLE
Error in npm install

### ISSUE THREAD

**Issue by Kstheking** [NJACKWinterOfCode/Learn-Japanese#12]
After the command `npm install` the output is
`npm ERR! write after end`
`npm ERR! write after end`
`npm ERR! write after end`

**Comment by bhaskarSingh** [comment]
can share the full error log, make sure you have update version of nodejs downloaded

**Comment by Kstheking** [comment]
@bhaskarSingh OH ok turns out that it was permission related error and got solved by `sudo npm install --unsafe-perm=true --allow-root` now after running `sudo npm start` The Konqueror app pops up for a moment and then it disappears

**Comment by Kstheking** [comment]
![screenshot from 2018-12-01 13-07-43](https://user-images.githubusercontent.com/35223915/49325585-2bcd9800-f56b-11e8-89e1-5ea5fba0d5be.png)
This is what the terminal looks like after `sudo npm start`

**Comment by bhaskarSingh** [comment]
Just go to localhost:3000 on your browser to run it

**Comment by roshniRam** [comment]
Yeah this will work without even removing warnings.

**Comment by Kstheking** [comment]
Yes this works, gratias ! :)
