### ISSUE TITLE
Fix the navbar expansion.

### ISSUE THREAD

**Issue by roshniRam** [NJACKWinterOfCode/Learn-Japanese#18]
Make the drop down list overlap the Japan-lover card instead of expanding the navbar.

![screenshot 139](https://user-images.githubusercontent.com/30633549/49433169-57ed5100-f7d7-11e8-8b42-a3a8eb4279de.png)

**Comment by ritwizsinha** [comment]
Is the issue closed?

**Comment by roshniRam** [comment]
No

**Comment by Kstheking** [comment]
@roshniRam @thebishaldeb fixed this issue

**Comment by saurabhshadow** [comment]
Is this issue closed?

**Comment by roshniRam** [comment]
No

**Comment by sudipt1999** [comment]
what does we need to do in it now
