### ISSUE TITLE
Design website logo.

### ISSUE THREAD

**Issue by roshniRam** [NJACKWinterOfCode/Learn-Japanese#2]
Design a logo for the website.

**Comment by Sai-Adarsh** [comment]
I would like to take this up!

**Comment by roshniRam** [comment]
Go for it 😃

**Comment by roshniRam** [comment]
@Sai-Adarsh whats the status?

**Comment by Kstheking** [comment]
![logo](https://user-images.githubusercontent.com/35223915/49389172-a94ffe80-f74b-11e8-9f6d-68764ec6c8cd.png)
How do you like this, @roshniRam ?

**Comment by roshniRam** [comment]
This is okay
@Sai-Adarsh what's the status with your design.

**Comment by Subhang23** [comment]
Can I take this up?

**Comment by Sai-Adarsh** [comment]
> This is okay
> @Sai-Adarsh what's the status with your design.

![logo](https://user-images.githubusercontent.com/21096774/49614396-24c1e200-f9d0-11e8-89cc-42984151c103.jpg)

@roshniRam How is this one ?

**Comment by Kstheking** [comment]
@Sai-Adarsh nice !

**Comment by roshniRam** [comment]
Great!
This logo is final.

**Comment by Sai-Adarsh** [comment]
@roshniRam ohkay, thanks. 👍

**Comment by Sai-Adarsh** [comment]
@roshniRam  gave PR
