### ISSUE TITLE
Suggest website name.

### ISSUE THREAD

**Issue by roshniRam** [NJACKWinterOfCode/Learn-Japanese#5]
Suggest some suitable name for the website in the comments.

**Comment by Sai-Adarsh** [comment]
How about Jap-Eng, Japeng, Jap-lish, Japlish ...

**Comment by Kstheking** [comment]
**Nihongo-Love**

**Comment by roshniRam** [comment]
Nihongo-Love is nice.

**Comment by roshniRam** [comment]
Yeah it is final. 👍
