### ISSUE TITLE
Change style of the start-learning button, navbar. 

### ISSUE THREAD

**Issue by roshniRam** [NJACKWinterOfCode/Learn-Japanese#7]
Shift the button to the left side of the login button with appropriate margins.

**Comment by thebishaldeb** [comment]
I would like to work on this. May I?

**Comment by Kstheking** [comment]
@thebishaldeb I guess you can but you also might wanna check out the pr I made regarding this issue 😊

**Comment by thebishaldeb** [comment]
@Kstheking My bad. I thought we need to ask first from the mentor for taking up an issue.
